export const wbsdata = [
  {
    element: "A - Preliminaries",
    level: "3",
    wbs: "0150",
    cbs: "C10150",
    desc: "Method-Related Cost",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "0300",
    cbs: "C20300",
    desc: "Fencing",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "0400",
    cbs: "C20400",
    desc: "Fencing",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "0400",
    cbs: "C20400",
    desc: "Road Restraint Systems",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "0500",
    cbs: "C20500",
    desc: "Drainage",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "0600",
    cbs: "C20600",
    desc: "Earthworks",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "1100",
    cbs: "C21100",
    desc: "Kerbs, Footways And Paved Areas",
  },
  {
    element: "BC - Boxed Culverts / Underpasses",
    level: "3",
    wbs: "1200",
    cbs: "C21200",
    desc: "Traffic Signs And Road Markings",
  },
  {
    element: "C - Central Reserve",
    level: "3",
    wbs: "0400",
    cbs: "C20400",
    desc: "Road Restraint Systems",
  },
  {
    element: "C - Central Reserve",
    level: "3",
    wbs: "0500",
    cbs: "C20500",
    desc: "Drainage",
  },
  {
    element: "C - Central Reserve",
    level: "3",
    wbs: "0600",
    cbs: "C20600",
    desc: "Earthworks",
  },
  {
    element: "C - Central Reserve",
    level: "3",
    wbs: "0700",
    cbs: "C20700",
    desc: "Pavements",
  },
  {
    element: "EO - Extended Overbridges",
    level: "3",
    wbs: "1300",
    cbs: "C21300",
    desc: "Road Lighting Columns, Brackets & CCTV Masts",
  },
  {
    element: "EO - Extended Overbridges",
    level: "3",
    wbs: "1400",
    cbs: "C21400",
    desc: "Electrical Work For Road Lighting And Traffic Signs",
  },
  {
    element: "EO - Extended Overbridges",
    level: "3",
    wbs: "1500",
    cbs: "C21600",
    desc: "Piling and Embedded Retaining Walls",
  },
  {
    element: "EO - Extended Overbridges",
    level: "3",
    wbs: "1600",
    cbs: "C21700",
    desc: "Structural Concrete",
  },
  {
    element: "EO - Extended Overbridges",
    level: "3",
    wbs: "1700",
    cbs: "C21700",
    desc: "Waterproofing for concrete structures",
  },
];

export const mapelement = [
  "A - Preliminaries",
  "B - Method Related - General",
  "BC - Boxed Culverts / Underpasses",
  "C - Central Reserve",
  "DG - DUAL SPAN GANTRY",
  "E - General / Enabling Works",
  "EO - Extended Overbridges",
  "EU - Extended Underbridges",
];

export const mapwbs = [
  "0100.10.10.10 (Establish Accommodation/Compounds)",
  "0100.10.10.20 (Erection of offices (incl. transportation))",
  "0100.10.10.30 (Information Boards)",
  "0100.10.40 (Land Rental and Rates)",
  "0100.10.40.10 (Land Rental)",
  "0100.10.50 (Site services - Water / Sewage / Site Power / Temporary Electrics)",
  "0100.10.50.30 (Sewage - Set-up)",
  "0100.10.50.60 (Temporary Electricity - Running Cost)",
  "0100.20.10.50 (Administration/Clerical)",
  "0100.20.20.20 (Accommodation & Subsistence)",
  "0100.20.20.60 (Site Specific Training)",
  "0100.20.30.10 (Contractors Consultants e.g. site based design supervision)",
  "0100.20.40.40 (Traffic Modelling (Lot 5))",
  "0100.30.10.45 (PCF Products by Contractor - Procurement)",
  "0100.30.20.80 (PCF Products by Overseeing Organisation - Handover)",
  "0100.50.10.10 (Security Personnel)",
  "0100.60.20.10 (Surveying Equipment for the Contractor - Setting out equipment )",
  "0100.60.40.50 (Steelwork Material Testing)",
  "0100.70.30.20 (Local Authority Licences / Orders (paid by the contractor))",
  "0150.10 (Attendant Labour and Equipment)",
  "0500.10.01.60 (Drains - Diameter  >=2400mm by jacking or thrustboring)",
];
